pipeline {
    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr:'10', daysToKeepStr:'28', artifactNumToKeepStr:'5', artifactDaysToKeepStr:'14'))
    }

    environment {
        ENV_FILE = credentials('fairwiki-env')
    }

    stages {
        stage('Compose/Startup') {
            steps {
                sh 'sudo docker compose stop'
                sh 'sudo docker compose --env-file $ENV_FILE up --pull always --force-recreate --detach'
            }
        }
    }
}
